import "./globals.css";
import Header from "./header";
import Navi from "./navi";

export const metadata = {
  title: "maro Anis",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main className="pt-20 max-w-screen-2xl m-auto flex gap-4">
          <Navi />
          <section className="flex-1 relative">{children}</section>
        </main>
      </body>
    </html>
  );
}
