import "./globals.css";
import Header from "./header";

// metadata
export const metadata = {
  title: "maro Anis",
  description: "Generated by create next app",
};

// style
const bodyStyle = "overflow-y-scroll bg-white dark:bg-neutral-800";
const mainStyle =
  "pt-28 md:pt-20 max-w-screen-2xl m-auto flex gap-4 overflow-hidden";
const sectionStyle = "w-full flex-1 relative px-2 md:px-4";

// RootLayout
export default function RootLayout({ children }) {
  return (
    <html lang="en" className=" ">
      <body className={bodyStyle}>
        <Header />
        <main className={mainStyle}>
          <section className={sectionStyle}>{children}</section>
        </main>
      </body>
    </html>
  );
}
